---
- name: run spring petclinic
  hosts: all
  become: yes
  tasks:
    - name: installing java
      ansible.builtin.apt:
        name: openjdk-17
        update_cache: yes
        state: present
    - name: downloading spring petclinic
      ansible.builtin.get_url:
        url: https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /home/ubuntu
    - name: running spring petclinic
      command: "java -jar /home/ubuntu/spring-petclinic-2.4.2.jar"