---
pool:
  name: 'Azure pipelines'
  vmImage: 'ubuntu-latest'

trigger:
- main

steps:
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
