---
- name: install apache server on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
---
- name: install java11 on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: openjdk-11-jdk
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present