---
- name: install java17 on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: openjdk-17-jdk
      ansible.builtin.apt:
        name: openjdk-17-jdk
        update_cache: yes
        state: present