---
- name: Install tomcat 10 on ubuntu 22
  hosts: all
  become: yes
  vars:
  java_package_name: openjdk-11-jdk
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: "{{ java_package_name }}"
        update_cache: yes
        state: present

        