### write a pipeline for build maven
### create s3 bucket
### Upload jar file to s3 bucket

---
pool:
  name: default
  vmImage: 'ubuntu-latest'

trigger:
- main

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      publishJUnitResults: yes
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkVersionOption: '1.17'
      jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
      mavenVersionOption: 'Path'
      mavenDirectory: '/opt/maven'

  - script: |
      aws s3 cp /home/ubuntu/myagent/_work/1/s/target/*.jar s3://spctest111/spc/
    displayName: Upload jar file to s3 bucket